# Generated by Django 5.0.7 on 2025-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinreviewer',
            name='area_of_specialization',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
    ]
