# Generated by Django 5.0.7 on 2025-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_joinreviewer_area_of_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
